FROM node:4.8.7-alpine@sha256:6eab176d2b3299509d20541757c2619f73ebd707d6b85f3e0ba994ae61e15861

LABEL maintainer "Leonardo Gatica <lgatica@protonmail.com>"

RUN apk add --no-cache --virtual build-dependencies make gcc g++ python

CMD [ "node" ]
