---
sudo: required

services:
  - docker

env:
  matrix:
    - env:
      VERSION: '9.0.0'
    - env:
      VERSION: '8.9.0'
    - env:
      VERSION: '6.11.5'
    - env:
      VERSION: '4.8.6'

install:
  - docker build -t "lgatica/node-build:$VERSION" "$VERSION"

script:
  - docker run --rm "lgatica/node-build:$VERSION" node --version

notifications:
  email: false
