---
sudo: required

services:
  - docker

env:
  matrix:
    - env:
      VERSION: '9.9.0'
    - env:
      VERSION: '8.10.0'
    - env:
      VERSION: '6.13.1'
    - env:
      VERSION: '4.8.7'

install:
  - docker build -t "lgatica/node-build:$VERSION" "$VERSION"

script:
  - docker run --rm "lgatica/node-build:$VERSION" node --version

notifications:
  email: false
