sudo: required

services:
  - docker

env:
  matrix :
    - env:
      VERSION: '8.7.0'
    - env:
      VERSION: '6.11.4'
    - env:
      VERSION: '4.8.4'

install:
  - docker build -t "lgatica/node-build:$VERSION" "$VERSION"

script:
  - docker run --rm "lgatica/node-build:$VERSION" node --version

notifications:
  email: false
