FROM node:9.1.0-alpine@sha256:293b6ce9d1153f3381ed351529761567d78ebf45ec71f4785ccdd7c823648062

LABEL maintainer "Leonardo Gatica <lgatica@protonmail.com>"

RUN apk add --no-cache --virtual build-dependencies make gcc g++ python

CMD [ "node" ]
