FROM node:9.0.0-alpine@sha256:803dbc6973165f0692253f45130b012dd5cdba02ab02f86931cc2a07d6e251b4

LABEL maintainer "Leonardo Gatica <lgatica@protonmail.com>"

RUN apk add --no-cache --virtual build-dependencies make gcc g++ python

CMD [ "node" ]
