FROM node:6.14.2-alpine@sha256:a4acb832fa0d6b120a4ceb3017a63e62ec35f69afdbad0544a7d57c08358041b

LABEL maintainer "Leonardo Gatica <lgatica@protonmail.com>"

RUN apk add --no-cache --virtual build-dependencies make gcc g++ python

CMD [ "node" ]
