FROM node:8.9.0-alpine@sha256:a179fb235e109c5ec2f26010a4f943699352b3aeb0189a5e6e3ca5b211f6f758

LABEL maintainer "Leonardo Gatica <lgatica@protonmail.com>"

RUN apk add --no-cache --virtual build-dependencies make gcc g++ python

CMD [ "node" ]
