FROM node:8.9.1-alpine@sha256:2966992de2ad29e349b34513ba130be195d289fe58deb80c84b032bbbbb6e92f

LABEL maintainer "Leonardo Gatica <lgatica@protonmail.com>"

RUN apk add --no-cache --virtual build-dependencies make gcc g++ python

CMD [ "node" ]
