FROM node:6.14.2-alpine@sha256:b7ef155babfb2a08c3fb9bc088868515c6880e2433f4b93d0d605abc8083c3e9

LABEL maintainer "Leonardo Gatica <lgatica@protonmail.com>"

RUN apk add --no-cache --virtual build-dependencies make gcc g++ python

CMD [ "node" ]
