FROM node:10.0.0-alpine@sha256:bde41330043a15e404c994614b774377445deff9c676320d842aa2c87a382924

LABEL maintainer "Leonardo Gatica <lgatica@protonmail.com>"

RUN apk add --no-cache --virtual build-dependencies make gcc g++ python

CMD [ "node" ]
