FROM node:4.8.7-alpine@sha256:d32fe67e80f388d0a40a20955e1aaec3e91c60e93dcdf90a0b0f881415d5a060

LABEL maintainer "Leonardo Gatica <lgatica@protonmail.com>"

RUN apk add --no-cache --virtual build-dependencies make gcc g++ python

CMD [ "node" ]
