FROM node:6.12.3-alpine@sha256:eeaabe13eca69f8000b22956cc8a2f9ac2b7f1b66c792938c844c0dbc9469b54

LABEL maintainer "Leonardo Gatica <lgatica@protonmail.com>"

RUN apk add --no-cache --virtual build-dependencies make gcc g++ python

CMD [ "node" ]
